### ISSUE TITLE
Not building/running on Python 3.12

### ISSUE THREAD

**Issue by cor3000** [henrywoo/kazam#50]
It could be I'm just making a beginners mistake, or not seeing something obvious.
I tried to  install this on my default python version 3.12 and it failed, while it works correctly on 3.11
Am correct to assume python 3.12 isn't supported yet and should stick with 3.11 for the time being?

**Comment by henrywoo** [comment]
Can you paste the errors?

**Comment by cor3000** [comment]
here everything I am doing, doing the same with python 3.11 just works (so I'm not blocked, just installed another python version to get kazam running ...)

```
[username@username-nb-red ~]$ pip --version
pip 24.0 from /usr/lib/python3.12/site-packages/pip (python 3.12)
[username@username-nb-red ~]$ pip install kazam
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
[username@username-nb-red ~]$ 
[username@username-nb-red ~]$ 
[username@username-nb-red ~]$ 
[username@username-nb-red ~]$ python -m venv path/to/venv
[username@username-nb-red ~]$ ^C
[username@username-nb-red ~]$ python -m venv ~/python/venv/p312
[username@username-nb-red ~]$ ~/python/venv/p312/bin/pip install kazam
Collecting kazam
  Downloading kazam-1.5.8-py3-none-any.whl.metadata (6.3 kB)
Collecting cmake (from kazam)
  Downloading cmake-3.29.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.1 kB)
Collecting distutils-extra-python (from kazam)
  Downloading distutils_extra_python-2.39.2-py3-none-any.whl.metadata (3.2 kB)
Collecting python-xlib (from kazam)
  Downloading python_xlib-0.33-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting dbus-python (from kazam)
  Downloading dbus-python-1.3.2.tar.gz (605 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 605.5/605.5 kB 3.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting hiq-python (from kazam)
  Downloading hiq_python-1.1.12-py3-none-any.whl.metadata (9.0 kB)
Collecting PyGObject (from kazam)
  Downloading pygobject-3.48.2.tar.gz (715 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 715.2/715.2 kB 4.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyxdg (from kazam)
  Downloading pyxdg-0.28-py2.py3-none-any.whl.metadata (567 bytes)
Collecting pycairo (from kazam)
  Using cached pycairo-1.26.0-cp312-cp312-linux_x86_64.whl
Collecting distro (from kazam)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting PyYAML (from hiq-python->kazam)
  Downloading PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting cachetools (from hiq-python->kazam)
  Downloading cachetools-5.3.3-py3-none-any.whl.metadata (5.3 kB)
Collecting psutil (from hiq-python->kazam)
  Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
INFO: pip is looking at multiple versions of hiq-python to determine which version is compatible with other requirements. This could take a while.
Collecting hiq-python (from kazam)
  Downloading hiq_python-1.1.11-py3-none-any.whl.metadata (9.1 kB)
  Downloading hiq_python-1.1.10-py3-none-any.whl.metadata (8.8 kB)
  Downloading hiq_python-1.1.9-py3-none-any.whl.metadata (8.8 kB)
  Downloading hiq_python-1.1.8-py3-none-any.whl.metadata (8.8 kB)
  Downloading hiq_python-1.1.7-py3-none-any.whl.metadata (5.0 kB)
  Downloading hiq_python-1.1.6-py3-none-any.whl.metadata (5.0 kB)
  Downloading hiq_python-1.1.5-py3-none-any.whl.metadata (4.9 kB)
INFO: pip is still looking at multiple versions of hiq-python to determine which version is compatible with other requirements. This could take a while.
  Downloading hiq_python-1.1.4-py3-none-any.whl.metadata (4.9 kB)
  Downloading hiq_python-1.1.3-py3-none-any.whl.metadata (4.9 kB)
  Downloading hiq_python-1.1.2-py3-none-any.whl.metadata (5.0 kB)
  Downloading hiq_python-1.1.1-py3-none-any.whl.metadata (5.2 kB)
Collecting cachetools~=5.2.0 (from hiq-python->kazam)
  Downloading cachetools-5.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting hiq-python (from kazam)
  Downloading hiq_python-1.1.0-py3-none-any.whl.metadata (5.2 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading hiq_python-1.0.5-py3-none-any.whl.metadata (5.2 kB)
  Downloading hiq_python-1.0.4-py3-none-any.whl.metadata (5.2 kB)
  Downloading hiq_python-1.0.3-py3-none-any.whl.metadata (5.2 kB)
  Downloading hiq_python-1.0.2-py3-none-any.whl.metadata (5.3 kB)
Collecting cachetools~=5.0.0 (from hiq-python->kazam)
  Downloading cachetools-5.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting hiq-python (from kazam)
  Downloading hiq_python-1.0.1-py3-none-any.whl.metadata (5.3 kB)
Collecting flask~=2.1.1 (from hiq-python->kazam)
  Downloading Flask-2.1.3-py3-none-any.whl.metadata (3.9 kB)
Collecting matplotlib~=3.5.1 (from hiq-python->kazam)
  Downloading matplotlib-3.5.3.tar.gz (35.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 9.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy~=1.22.3 (from hiq-python->kazam)
  Downloading numpy-1.22.4.zip (11.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 8.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    super().__init__(
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 745, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/tmp/pip-build-env-q511k3sq/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
```

reading the release notes of python 3.12 indicates that **distutils** was removed by default, so maybe there's an easy fix I am missing

https://www.python.org/downloads/release/python-3120/

> The deprecated smtpd and distutils modules have been removed (see [PEP 594](https://peps.python.org/pep-0594/) and [PEP 632](https://peps.python.org/pep-0632/). The **setuptools** package continues to provide the distutils module.

trying to install **setuptools**, also fails ... that's when I rolled back to python 3.11

```
[username@username-nb-red ~]$ ~/python/venv/p312/bin/pip install setuputils
Collecting setuputils
  Downloading setuputils-1.0.3.tar.gz (9.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      <string>:44: SyntaxWarning: invalid escape sequence '\/'
      Traceback (most recent call last):
        File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/username/python/venv/p312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8hhepeuq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8hhepeuq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-8hhepeuq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-8hhepeuq/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 40, in <module>
        File "/tmp/pip-install-chphwmp4/setuputils_29cba0ae6c2f453cb598859c06b5d1f1/setuputils.py", line 62, in <module>
          from itertools import chain, dropwhile, islice, izip, takewhile
      ImportError: cannot import name 'izip' from 'itertools' (unknown location)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by nsheff** [comment]
I am also experiencing this error. I have not been able to find a workaround, I cannot get kazam working in ubuntu 24.04, which has python3.12 as the default version

**Comment by henrywoo** [comment]
Please try the latest version:

`pip install kazam==1.5.9`

This should fix the issue.

**Comment by cor3000** [comment]
sorry from my side I still can't install it... I still think I'm just holding it wrong

```
robert@cor3000-NB-L14:py312$ . bin/activate
(py312) robert@cor3000-NB-L14:py312$ python --version
Python 3.12.5
(py312) robert@cor3000-NB-L14:py312$ pip --version 
pip 24.2 from /home/robert/devres/py312/lib/python3.12/site-packages/pip (python 3.12)


(py312) robert@cor3000-NB-L14:py312$ pip install kazam==1.5.9


Collecting kazam==1.5.9
  Using cached kazam-1.5.9-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: cmake in ./lib/python3.12/site-packages (from kazam==1.5.9) (3.30.2)
Collecting distutils-extra-python (from kazam==1.5.9)
  Using cached distutils_extra_python-2.39.2-py3-none-any.whl.metadata (3.2 kB)
Collecting python-xlib (from kazam==1.5.9)
  Using cached python_xlib-0.33-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting dbus-python (from kazam==1.5.9)
  Using cached dbus_python-1.3.2-cp312-cp312-linux_x86_64.whl
Collecting hiq-python (from kazam==1.5.9)
  Using cached hiq_python-1.1.14-py3-none-any.whl.metadata (9.2 kB)
Collecting PyGObject (from kazam==1.5.9)
  Using cached pygobject-3.48.2-cp312-cp312-linux_x86_64.whl
Collecting pyxdg (from kazam==1.5.9)
  Using cached pyxdg-0.28-py2.py3-none-any.whl.metadata (567 bytes)
Collecting pycairo (from kazam==1.5.9)
  Using cached pycairo-1.26.1-cp312-cp312-linux_x86_64.whl
Collecting distro (from kazam==1.5.9)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting PyYAML (from hiq-python->kazam==1.5.9)
  Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting cachetools (from hiq-python->kazam==1.5.9)
  Using cached cachetools-5.5.0-py3-none-any.whl.metadata (5.3 kB)
Collecting psutil (from hiq-python->kazam==1.5.9)
  Using cached psutil-6.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Collecting py-itree (from hiq-python->kazam==1.5.9)
  Using cached py_itree-0.0.21.tar.gz (485 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting urllib3 (from hiq-python->kazam==1.5.9)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting requests (from hiq-python->kazam==1.5.9)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting rich (from hiq-python->kazam==1.5.9)
  Using cached rich-13.8.0-py3-none-any.whl.metadata (18 kB)
Collecting six>=1.10.0 (from python-xlib->kazam==1.5.9)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting charset-normalizer<4,>=2 (from requests->hiq-python->kazam==1.5.9)
  Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->hiq-python->kazam==1.5.9)
  Using cached idna-3.8-py3-none-any.whl.metadata (9.9 kB)
Collecting certifi>=2017.4.17 (from requests->hiq-python->kazam==1.5.9)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting markdown-it-py>=2.2.0 (from rich->hiq-python->kazam==1.5.9)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->hiq-python->kazam==1.5.9)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->hiq-python->kazam==1.5.9)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached kazam-1.5.9-py3-none-any.whl (326 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Using cached distutils_extra_python-2.39.2-py3-none-any.whl (20 kB)
Using cached hiq_python-1.1.14-py3-none-any.whl (91 kB)
Using cached python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Using cached pyxdg-0.28-py2.py3-none-any.whl (49 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached cachetools-5.5.0-py3-none-any.whl (9.5 kB)
Using cached psutil-6.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (290 kB)
Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Using cached rich-13.8.0-py3-none-any.whl (241 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cached idna-3.8-py3-none-any.whl (66 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Building wheels for collected packages: py-itree
  Building wheel for py-itree (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for py-itree (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [445 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying itree/version.py -> build/lib.linux-x86_64-cpython-312/itree
      running egg_info
      writing py_itree.egg-info/PKG-INFO
      writing dependency_links to py_itree.egg-info/dependency_links.txt
      writing top-level names to py_itree.egg-info/top_level.txt
      reading manifest file 'py_itree.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'WORKSPACE'
      warning: no files found matching 'CONTRIBUTING.md'
      warning: no files found matching '*.cc' under directory '.'
      adding license file 'LICENSE'
      writing manifest file 'py_itree.egg-info/SOURCES.txt'
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.build' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.build' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.build' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.build' to be distributed and are
              already explicitly excluding 'itree.build' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.build.CMakeFiles' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.build.CMakeFiles' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.build.CMakeFiles' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.build.CMakeFiles' to be distributed and are
              already explicitly excluding 'itree.build.CMakeFiles' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.build.build_pybind11' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.build.build_pybind11' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.build.build_pybind11' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.build.build_pybind11' to be distributed and are
              already explicitly excluding 'itree.build.build_pybind11' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.build.build_pybind11.CMakeFiles' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.build.build_pybind11.CMakeFiles' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.build.build_pybind11.CMakeFiles' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.build.build_pybind11.CMakeFiles' to be distributed and are
              already explicitly excluding 'itree.build.build_pybind11.CMakeFiles' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.pybind11' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.pybind11' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.pybind11' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.pybind11' to be distributed and are
              already explicitly excluding 'itree.pybind11' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.pybind11.include.pybind11' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.pybind11.include.pybind11' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.pybind11.include.pybind11' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.pybind11.include.pybind11' to be distributed and are
              already explicitly excluding 'itree.pybind11.include.pybind11' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.pybind11.include.pybind11.detail' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.pybind11.include.pybind11.detail' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.pybind11.include.pybind11.detail' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.pybind11.include.pybind11.detail' to be distributed and are
              already explicitly excluding 'itree.pybind11.include.pybind11.detail' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.pybind11.include.pybind11.stl' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.pybind11.include.pybind11.stl' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.pybind11.include.pybind11.stl' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.pybind11.include.pybind11.stl' to be distributed and are
              already explicitly excluding 'itree.pybind11.include.pybind11.stl' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      /tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'itree.pybind11.tools' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'itree.pybind11.tools' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'itree.pybind11.tools' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'itree.pybind11.tools' to be distributed and are
              already explicitly excluding 'itree.pybind11.tools' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      copying itree/CMakeLists.txt -> build/lib.linux-x86_64-cpython-312/itree
      copying itree/common.cpp -> build/lib.linux-x86_64-cpython-312/itree
      running build_ext
      Traceback (most recent call last):
        File "/home/robert/devres/py312/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "/home/robert/devres/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/robert/devres/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robert/devres/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 100, in <module>
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 953, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 972, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 384, in run
          self.run_command("build")
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 972, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-vykud2rn/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 972, in run_command
          cmd_obj.run()
        File "<string>", line 53, in run
        File "<string>", line 60, in _check_build_environment
        File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py-itree
Failed to build py-itree
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (py-itree)
(py312) robert@cor3000-NB-L14:py312$ 

(py312) robert@cor3000-NB-L14:py312$ cmake --version
cmake version 3.30.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(py312) robert@cor3000-NB-L14:py312$ uname -a
Linux cor3000-NB-L14 6.10.6-10-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:17:40 UTC 2024 x86_64 GNU/Linux
(py312) robert@cor3000-NB-L14:py312$ 
```

**Comment by cor3000** [comment]
sorry I never got back to this, the issues no longer apply in version 2.0.0
